import argparse
from pathlib import Path


def create_parser():
    parser = argparse.ArgumentParser(add_help=True)
    parser.add_argument('train_df_path', type=Path)
    parser.add_argument('test_df_path', type=Path)
    parser.add_argument('data_path', type=Path)
    parser.add_argument('output_path', type=Path)
    parser.add_argument('--checkpoint_path', default=[], action='append')
    parser.add_argument('--stack_size', default=16, type=int)
    parser.add_argument('--train_batch', default=64, type=int)
    parser.add_argument('--train_workers', default=8, type=int)
    parser.add_argument('--train_samples_per_seg', default=1, type=int)
    parser.add_argument('--train_frame_sampling', default='random', type=str)
    parser.add_argument('--test_batch', default=256, type=int)
    parser.add_argument('--test_workers', default=8, type=int)
    parser.add_argument('--test_samples_per_seg', default=10, type=int)
    parser.add_argument('--test_frame_sampling', default='uniform', type=str)
    parser.add_argument('--opt', default='adam', type=str)
    parser.add_argument('--lr', default=1e-4, type=float)
    parser.add_argument('--dropout', default=0.5, type=float)
    parser.add_argument('--epochs', default=1000, type=int)
    parser.add_argument('--run_tags', default=['baseline', 'lr', 'train_batch', 'dropout'], action='append')
    parser.add_argument('--tag', default=None, type=str)
    parser.add_argument('--rgb_height', default=226, type=int)
    parser.add_argument('--flow_height', default=224, type=int)
    parser.add_argument('--crop_size', default=224, type=int)
    parser.add_argument('--train_only', action='store_true')
    parser.add_argument('--test_only', action='store_true')
    parser.add_argument('--test_frequency', default=10, type=int)
    parser.add_argument('--hidden_units', default='512,512,512', type=str)
    parser.add_argument('--extract_features', action='store_true')
    parser.add_argument('--features_path', default=None, type=Path)
    parser.add_argument('--adv_cat_df', default=None, type=Path)
    parser.add_argument('--feat_frequency', default=1.0, type=float)
    parser.add_argument('--weight_decay', default=5e-5, type=float)
    parser.add_argument('--features_modality', default='rgb_flow', type=str)
    parser.add_argument('--act_mod_dataset_pickle', default=None, type=Path)
    parser.add_argument('--prepend_cols_to_build_frames_path', default=None, action='append')
    parser.add_argument('--load_for_new_dataset', action='store_true')
    parser.add_argument('--individual_feat_files', action='store_true')
    parser.add_argument('--train_only_layer', default=None, action='append')
    parser.add_argument('--filter_class', default=None, action='append')
    parser.add_argument('--filter_seg_id', default=None, action='append')
    parser.add_argument('--filter_mode', default='remove', type=str, choices=('remove', 'keep'))
    parser.add_argument('--keep_video_shorter_than', default=None, type=float)
    parser.add_argument('--debug', action='store_true')
    parser.add_argument('--force_end_to_end', action='store_true')
    parser.add_argument('--allow_new_logits', action='store_true')
    parser.add_argument('--find_prototypes', action='store_true')
    parser.add_argument('--prototypes', action='append')
    parser.add_argument('--force_classes', default=None, type=int)
    parser.add_argument('--dump_tracklets', default=None, type=Path)
    parser.add_argument('--stride', default=1, type=int)
    parser.add_argument('--obj_batch_size', default=24, type=int)
    parser.add_argument('--output_channels', default=512, type=int)
    parser.add_argument('--proto_pickle', default=None, type=Path)
    parser.add_argument('--filter_if_no_objects', action='store_true')
    parser.add_argument('--version', default=None, type=str)
    parser.add_argument('--skip_if_exists', action='store_true')
    parser.add_argument('--margin', default=0, type=int)
    parser.add_argument('--add_mlp_to_act_mod_vf', action='store_true')
    parser.add_argument('--no_antonyms', action='store_true')
    parser.add_argument('--no_relu', action='store_true')
    parser.add_argument('--feat_dim', default=None, type=int)

    parser.add_argument('--s3d_init_folder', type=Path, default=None)
    parser.add_argument('--s3d_video_f', default='s3d_features', type=str)

    return parser